use_frameworks!

platform :ios, '9.0'

target 'PasswordValidator_Example' do
  pod 'PasswordValidator', :path => '../'

  target 'PasswordValidator_Tests' do
    inherit! :search_paths

    
  end
end
